"""baseline existing schema

Revision ID: 05a4548b3ab6
Revises: 
Create Date: 2026-09-05 18:36:09.244492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '05a4548b3ab6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
