"""add user lists and social tables

Revision ID: 806336d33ba8
Revises: 05a4548b3ab6
Create Date: 2026-09-05 18:47:36.632410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '806336d33ba8'
down_revision: Union[str, None] = '05a4548b3ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_lists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('is_ranked', sa.Boolean(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_lists_entity_type', 'user_lists', ['entity_type'], unique=False)
    op.create_index(op.f('ix_user_lists_slug'), 'user_lists', ['slug'], unique=True)
    op.create_index(op.f('ix_user_lists_user_id'), 'user_lists', ['user_id'], unique=False)
    op.create_index('ix_user_lists_user_visibility', 'user_lists', ['user_id', 'visibility'], unique=False)
    op.create_table('list_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('list_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('parent_comment_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['user_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['list_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_list_comments_list_id'), 'list_comments', ['list_id'], unique=False)
    op.create_table('list_follows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('list_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['user_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id', 'user_id', name='uq_list_follow_once')
    )
    op.create_index(op.f('ix_list_follows_list_id'), 'list_follows', ['list_id'], unique=False)
    op.create_index(op.f('ix_list_follows_user_id'), 'list_follows', ['user_id'], unique=False)
    op.create_table('list_likes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('list_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['user_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id', 'user_id', name='uq_list_like_once')
    )
    op.create_index(op.f('ix_list_likes_list_id'), 'list_likes', ['list_id'], unique=False)
    op.create_index(op.f('ix_list_likes_user_id'), 'list_likes', ['user_id'], unique=False)
    op.create_table('user_list_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('list_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['user_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id', 'entity_id', name='uq_list_entity_once')
    )
    op.create_index('ix_list_items_list_position', 'user_list_items', ['list_id', 'position'], unique=False)
    op.create_index(op.f('ix_user_list_items_entity_id'), 'user_list_items', ['entity_id'], unique=False)
    op.create_index(op.f('ix_user_list_items_list_id'), 'user_list_items', ['list_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_list_items_list_id'), table_name='user_list_items')
    op.drop_index(op.f('ix_user_list_items_entity_id'), table_name='user_list_items')
    op.drop_index('ix_list_items_list_position', table_name='user_list_items')
    op.drop_table('user_list_items')
    op.drop_index(op.f('ix_list_likes_user_id'), table_name='list_likes')
    op.drop_index(op.f('ix_list_likes_list_id'), table_name='list_likes')
    op.drop_table('list_likes')
    op.drop_index(op.f('ix_list_follows_user_id'), table_name='list_follows')
    op.drop_index(op.f('ix_list_follows_list_id'), table_name='list_follows')
    op.drop_table('list_follows')
    op.drop_index(op.f('ix_list_comments_list_id'), table_name='list_comments')
    op.drop_table('list_comments')
    op.drop_index('ix_user_lists_user_visibility', table_name='user_lists')
    op.drop_index(op.f('ix_user_lists_user_id'), table_name='user_lists')
    op.drop_index(op.f('ix_user_lists_slug'), table_name='user_lists')
    op.drop_index('ix_user_lists_entity_type', table_name='user_lists')
    op.drop_table('user_lists')
    # ### end Alembic commands ###
